buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://storage.googleapis.com/r8-releases/raw")
        }
       maven {
            url = uri("https://jitpack.io")
       }
    }
    dependencies {
        //noinspection GradleDependency
        classpath 'com.android.tools:r8:8.7.18'
        //noinspection AndroidGradlePluginVersion
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.3'
    }
}

allprojects {

    //安卓端分支 使用模拟器进行测试
    ext {
        appName = 'Magic Ling Pixel Dungeon'
        appPackageName = 'com.ansdomagiclingpixeldungeon.ling'

        appVersionCode = 2026011300
        appVersionName = '0.9.1.6-D7'

        appJavaCompatibility = JavaVersion.VERSION_1_8

        appAndroidCompileSDK = 35
        appAndroidMinSDK = 21
        appAndroidTargetSDK = 33

        gdxVersion = '1.11.0'
        gdxControllersVersion = '2.2.4'
    }

    version = appVersionName

    repositories {
        google()
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
        maven {
            url = uri("https://jitpack.io")
        }
    }

}